import Head from "next/head";
import Image from "next/image";

import Player from "../components/myPlayer";


import mainIMG from "../public/img/mainImg.png";

import HydrotreatingSwiper from "../components/Hydrotreating/hydrotreatingSwiper";
import Modal from '../components/Modal'

export default function Home() {
  return (
    <div className="container">
      <Head>
        <title>ЭОР</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="main">
        <div className="main-scroll">
          <section className="home">
            <div className="centered">
              <strong><h1>
                Электронный образовательный ресурс</h1>
              </strong>
              <strong><p>
                По специальностям "Оператор технологических установок", "Слесарь
                по ремонту технологических установок"</p>
              </strong>
            </div>
            <Image src={mainIMG} alt="" className="mainImg" />
          </section>
          <section id="about">
            <div className="intro">
              <div className="intro-desc">
                <h1>Аннотация</h1>
                <ul>
                  <li>
                    <p>
                      Электронный образовательный ресурс разработан по
                      специальностям "Оператор технологических установок",
                      "Слесарь по ремонту технологических установок".
                    </p>
                  </li>
                  <li>
                    <p>
                      Предназначен для изучения учебных предметов “Специальная
                      технология (Оператор технологических установок, слесарь по
                      ремонту технологических установок)” и “Производственное
                      обучение» по квалификациям: “Оператор технологических
                      установок", "Слесарь по ремонту технологических установок".
                    </p>
                  </li>
                  <li>
                    <p>
                      Целью проекта является эффективная организация учебного
                      процесса: проведение теоретических практических занятий,
                      организация самостоятельной работы и контроля усвоения
                      знаний учащихся.
                    </p>
                  </li>
                </ul>
              </div>
              <div className="introVideo">
                {/* https://www.youtube.com/embed/gucTe2zmJ-8 */}
                <Player src={"https://youtu.be/INN6d-CL6KU"} />
                <Player src={"https://www.youtube.com/embed/INN6d-CL6KU"} />
                <div className="intro-help-block"></div>
                {/* <div className="intro__video-test">Загрузка відео</div> */}
                {/* <div className="intro__video-test">Загрузка відео</div> */}
              </div>
            </div>
          </section>
          <section style={{ position: 'relative' }} id="service">
            <Modal />
            <HydrotreatingSwiper />
          </section>
        </div>
      </main >
      <footer className="footer"></footer>
    </div >
  );
}
